name: cycleGAN
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.7.2
  - appdirs=1.4.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - certifi=2025.10.5
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda-version=12.9
  - dataclasses=0.8
  - dbus=1.13.6
  - docker-pycreds=0.4.0
  - eval_type_backport=0.2.2
  - exceptiongroup=1.2.2
  - expat=2.7.1
  - ffmpeg=4.3.2
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fvcore=0.1.5.post20221221
  - gds-tools=1.14.1.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - harfbuzz=4.2.0
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jasper=2.0.33
  - jpeg=9e
  - keyutils=1.6.3
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcufile=1.14.1.1
  - libcurl=7.87.0
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm13=13.0.1
  - libnghttp2=1.51.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libnuma=2.0.18
  - libogg=1.3.5
  - libopencv=4.5.5
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpng=1.6.43
  - libpq=14.5
  - libprotobuf=3.19.6
  - libsodium=1.0.18
  - libsqlite=3.41.2
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4.20240210
  - nettle=3.7.3
  - nspr=4.37
  - nss=3.89.1
  - opencv=4.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py-opencv=4.5.5
  - pycparser=2.21
  - pydantic=1.10.22
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - python_abi=3.10
  - pyyaml=6.0.3
  - qt=5.12.9
  - rdma-core=58.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tabulate=0.9.0
  - termcolor=2.2.0
  - tk=8.6.12
  - tqdm=4.67.1
  - typing=3.10.0.0
  - urllib3=1.26.15
  - wheel=0.38.4
  - x264=1!161.3030
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - asttokens==2.2.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - cachetools==5.3.0
      - click==8.1.3
      - comm==0.1.3
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==4.4.2
      - dictparse==1.4
      - executing==1.2.0
      - filelock==3.12.0
      - fonttools==4.39.3
      - fsspec==2024.6.1
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - gpustat==1.1
      - grpcio==1.54.0
      - h5py==3.8.0
      - imagecodecs==2025.3.30
      - imageio==2.28.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.5.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipykernel==6.22.0
      - ipython==8.12.0
      - jedi==0.18.2
      - jinja2==3.1.4
      - joblib==1.2.0
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - kinematics==0.1.7
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - lightning-utilities==0.15.2
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - nest-asyncio==1.5.6
      - networkx==3.2.1
      - numpy==2.2.6
      - oauthlib==3.2.2
      - packaging==23.1
      - pandas==2.3.3
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - platformdirs==3.2.0
      - portalocker==3.2.0
      - proglog==0.1.10
      - prompt-toolkit==3.0.38
      - protobuf==4.22.3
      - psutil==5.9.5
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.15.1
      - pylibtiff==0.7.0
      - pymo==0.2.0
      - pymongo==3.13.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyzmq==25.0.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.22.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.43.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - sympy==1.14.0
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2023.12.9
      - torchgeometry==0.1.2
      - torchmetrics==1.8.2
      - tornado==6.3
      - traitlets==5.9.0
      - triton==3.3.0
      - typing-extensions==4.15.0
      - tzdata==2023.3
      - v==1
      - wandb==0.22.3
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - zipp==3.15.0
prefix: /media/tien/SSD-NOT-OS/nguyen_projects/.conda/envs/cycleGAN
